name: acs_1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  introduction_screen: ^3.0.2
  get: ^4.6.1
  persistent_bottom_nav_bar: ^4.0.2
  pandabar: ^0.1.2
  http: ^0.13.4
  loading_indicator: ^3.0.3
  get_storage: ^2.0.3
  velocity_x: ^3.4.0
  dio: ^4.0.6
  global_configuration: ^2.0.0-nullsafety.1
  flutter_easyloading: ^3.0.3
  date_picker_timeline: ^1.2.3
  intl: ^0.17.0
  jiffy: ^5.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Comfortaa-Bold
      fonts:
        - asset: assets/fonts/Comfortaa-Bold.ttf
    - family: Comfortaa-Light
      fonts:
        - asset: assets/fonts/Comfortaa-Light.ttf
    - family: Comfortaa-Regular
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
    - family: Comfortaa-Medium
      fonts:
        - asset: assets/fonts/Comfortaa-Medium.ttf
    - family: Comfortaa-SemiBold
      fonts:
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
    - family: CrimsonPro-Light
      fonts:
        - asset: assets/fonts/CrimsonPro-Light.ttf
    - family: CrimsonPro-Bold
      fonts:
        - asset: assets/fonts/CrimsonPro-Bold.ttf
    - family: CrimsonPro-ExtraLight
      fonts:
        - asset: assets/fonts/CrimsonPro-ExtraLight.ttf
    - family: CrimsonPro-Medium
      fonts:
        - asset: assets/fonts/CrimsonPro-Medium.ttf
    - family: CrimsonPro-Regular
      fonts:
        - asset: assets/fonts/CrimsonPro-Regular.ttf
    - family: CrimsonPro-SemiBold
      fonts:
        - asset: assets/fonts/CrimsonPro-SemiBold.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
